name: build

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
jobs:
  build-ref:
    name: build ref
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ github.event.inputs.nodeVer }}
      - run: yarn packs
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.inputs.ref }}
          path: ./
