name: Build Ref

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'The branch, tag or SHA to checkout'
        required: true
        default: 'master'
      nodeVersion:
        description: 'Nodejs version'
        required: true
        default: 'x'
      deliveryExperimental:
        description: 'Should delivery a experimental to registry'
        required: true
        default: false
      runTest:
        description: 'Should run test'
        required: true
        default: true

jobs:
  build-ref:
    name: Build on ${{ github.event.inputs.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Set delivery info
        run: |
          echo "DELIVERY_VERSION=${{ env.DELIVERY_VERSION }}" >> $GITHUB_ENV
          echo "NPM_TAG=${{ env.NPM_TAG }}" >> $GITHUB_ENV
        env:
          DELIVERY_VERSION: >
            0.0.0-experimental-
            ${{ join([github.job, github.sha, github.run_id, github.run_number], '-') }}
          NPM_TAG: experimental

      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ github.event.inputs.nodeVersion }}
      - run: yarn install
      - run: yarn build

      # Delivery to NPM
      # - shell: pwsh
      #   run: yarn config set npmAuthToken "$env:NPM_TOKEN"
      # - run: yarn delivery
      #   if: ${{ github.event.inputs.deliveryExperimental }}

      # Delivery to GH Registry
      - run: yarn config set npmPublishRegistry 'https://npm.pkg.github.com/'
      - shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn config set npmAuthToken "$env:GITHUB_TOKEN"
      - run: yarn delivery
        if: ${{ github.event.inputs.deliveryExperimental }}

      - run: echo published ${{ env.DELIVERY_VERSION }}

      - run: yarn test
        if: ${{ github.event.inputs.runTest }}
