name: PR

on:
  - pull_request
jobs:
  pull-request:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 12
          - x
    name: PR Node ${{ matrix.node }} PR ${{ github.event.pull_request.html_url }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn ci
