name: Push

on:
  - push
jobs:
  push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 12
          - x
    name: Push Node ${{ matrix.node }} SHA ${{ github.event.after }} 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn ci
