name: Release Experimental

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'The branch, tag or SHA to checkout'
        required: true
        default: 'master'

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 12
          - x
    name: CI Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn ci
  release:
    name: Release Experimental
    needs:
      - ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}
          fetch-depth: 2 # set ver issue
      - uses: actions/setup-node@v2-beta
      - run: yarn install
      - run: yarn build
      # GPR
      - run: yarn config set npmPublishRegistry 'https://npm.pkg.github.com/'
      - shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn config set npmAuthToken "$env:GITHUB_TOKEN"
      - run: yarn delivery-expr
      # NPM
      # - run: yarn config set npmPublishRegistry 'https://registry.npmjs.org/'
      # - shell: pwsh
      #   env:
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   run: yarn config set npmAuthToken "$env:NPM_TOKEN"
      # - run: yarn delivery-expr
